<?php

namespace DroidInfotech\DroidBundle\Repository;

/**
 * EventImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
