<?php

namespace DroidInfotech\DroidBundle\Repository;

/**
 * EventScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventScheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
