<?php

namespace DroidInfotech\DroidBundle\Repository;

/**
 * ExhibitorCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExhibitorCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
