<?php

namespace DroidInfotech\DroidBundle\Repository;

/**
 * exhibitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExhibitorRepository extends \Doctrine\ORM\EntityRepository
{
}
