<?php

namespace DroidInfotech\DroidBundle\Repository;

/**
 * MapsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapsRepository extends \Doctrine\ORM\EntityRepository
{
}
