<?php

namespace DroidInfotech\DroidBundle\Repository;

/**
 * Notification_messageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Notification_messageRepository extends \Doctrine\ORM\EntityRepository
{
}
