<?php

namespace DroidInfotech\DroidBundle\Repository;

/**
 * UserFavouriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFavouriteRepository extends \Doctrine\ORM\EntityRepository
{
}
