<?php

namespace DroidInfotech\DroidBundle\Entity;

/**
 * AnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
